Added support for zone management
dominicdesu/tchaikovsky pull request #1
Opened 2016-10-20 20:03 UTC by Yannic-HAW

Hi,

i have added support for ZoneManagement to the tchaikovsky lib.
Just call .createZone() one the desired speaker and pass a list of speaker objects to add to the zone. Afterwards the speaker object you called with .createZone() will become the zone master and all speakers in the passed list will become slaves. 

To revoke the group just call .releaseZone() on the master speaker. 

Code is tested and works just fine for me. Maybe it is a useful feature you would like to pull into our branch.

2016-10-22 10:18 UTC, dominicdesu commented
Awesome, thank you so much for contributing your implementation of the zone management!!
I will review the changes asap and come back to you in case of any questions.

2016-11-09 16:12 UTC, dominicdesu requested changes
Hi @Yannic-HAW, sorry for the late review, I was very busy the last days. I added some small comments, could you check if it makes sense to change it before merging?

2016-11-09 16:12 UTC, dominicdesu commented on src/main/java/de/kaizencode/tchaikovsky/speaker/ZoneManager.java
> +    public RemoteZoneItem createZone(String[] speakers) throws SpeakerException;
Could you return the ZoneItem interface here instead of the implementation?

2016-11-09 16:12 UTC, dominicdesu commented on src/main/java/de/kaizencode/tchaikovsky/speaker/remote/RemoteZoneManager.java
> +    public RemoteZoneItem createZone(String[] speakers) throws SpeakerException {
Could you return the ZoneItem interface here instead of the implementation?

2016-11-09 16:12 UTC, dominicdesu commented on src/main/java/de/kaizencode/tchaikovsky/speaker/remote/RemoteSpeaker.java
> +    public void createZone(List<Speaker> speakerItems) throws SpeakerException {
What do you think about putting createZone and releaseZone into the RemoteZoneManager class and just returning the ZoneManager interface instead? (Similar as done with the Volume interface). This way, users have access to all methods of the ZoneManager.

2016-11-09 16:12 UTC, dominicdesu commented on src/main/java/de/kaizencode/tchaikovsky/speaker/remote/RemoteZoneManager.java
> +    private final Logger logger = LoggerFactory.getLogger(RemoteVolume.class);
I guess this should be RemoteZoneManager.class?

2016-11-09 18:28 UTC, Yannic-HAW commented
Hi,
i have implemented your suggested changes and have also implemented the onZoneChange callback.
You had some code disabled in ZoneInfo interface and i think you did that because of the messed up returned Variant by the leadPlayerName parameter. 
I have changed that part a bit and added isLeadPlayer() and getLeadPlayerID() methods. 

I dont know if it just works for the panasonic models but with panasonic it works just fine that way.

2016-11-09 19:07 UTC, dominicdesu approved these changes
Thanks!

2016-11-09 19:08 UTC, merged